-- =============================================================================
-- Schema: Cloud Engineer Portfolio & Operations Platform
-- =============================================================================
-- Provided by the academy. You normally do not edit this file.
--
-- Locally, Docker runs this automatically the first time the postgres volume is
-- created. In AWS you will run it against your RDS instance (Milestone 3).
-- =============================================================================

CREATE TABLE IF NOT EXISTS profile (
    id           INTEGER PRIMARY KEY DEFAULT 1,
    name         TEXT NOT NULL,
    title        TEXT NOT NULL,
    email        TEXT NOT NULL,
    location     TEXT NOT NULL,
    bio          TEXT NOT NULL,
    linkedin_url TEXT,
    github_url   TEXT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- enforce a single profile row
    CONSTRAINT profile_singleton CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS skills (
    id            SERIAL PRIMARY KEY,
    category      TEXT NOT NULL,          -- e.g. 'Cloud', 'IaC', 'Containers'
    name          TEXT NOT NULL,          -- e.g. 'AWS', 'Terraform'
    level         SMALLINT NOT NULL DEFAULT 3 CHECK (level BETWEEN 1 AND 5),
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS certifications (
    id             SERIAL PRIMARY KEY,
    name           TEXT NOT NULL,         -- e.g. 'AWS Certified Cloud Practitioner'
    issuer         TEXT NOT NULL,         -- e.g. 'Amazon Web Services'
    issued_date    DATE,
    credential_url TEXT,
    status         TEXT NOT NULL DEFAULT 'earned'
                   CHECK (status IN ('earned', 'in-progress', 'planned'))
);

CREATE TABLE IF NOT EXISTS projects (
    id            SERIAL PRIMARY KEY,
    title         TEXT NOT NULL,
    summary       TEXT NOT NULL,
    description   TEXT NOT NULL,
    tech          TEXT[] NOT NULL DEFAULT '{}',  -- e.g. {Terraform,EKS,GitHubActions}
    repo_url      TEXT,
    demo_url      TEXT,
    featured      BOOLEAN NOT NULL DEFAULT false,
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_skills_order        ON skills (display_order);
CREATE INDEX IF NOT EXISTS idx_projects_order      ON projects (display_order);
CREATE INDEX IF NOT EXISTS idx_certifications_date ON certifications (issued_date DESC);
